### ISSUE TITLE
TypeError: DiscretizedIIDProcess() takes no arguments

### ISSUE THREAD

**Issue by sbenthall** [EconForge/dolo.py#209]
Here, the `DiscretizedIIDProcess` constructor is called with two arguments:
https://github.com/EconForge/dolo.py/blob/3c73f4cd7838a4913dbdf7bbd559e80570b0a5e8/dolo/numeric/processes.py#L121

However, that class takes no arguments in its constructor?

I get this error in a call to `find_steady_state(model)` in dolark which winds up with this message:

`TypeError: DiscretizedIIDProcess() takes no arguments`

If necessary I can try to narrow down the conditions for the error.

**Comment by albop** [comment]
Yes, I think this definition of `DiscretizedIIDProcess` in processes.py is obsolete and should be removed. It should be replaced by FiniteDistribution from `distribution.py`.

**Comment by sbenthall** [comment]
Any update on this issue?

**Comment by albop** [comment]
Have you tried using FiniteDistribution instead of DiscretizedIIDProcess ?

**Comment by sbenthall** [comment]
Ah, are you saying you would like this as a PR?

**Comment by albop** [comment]
Oh, if you could do a PR, that would be great. You just need to remove DiscretizedIIDProcess. But if you are importing it from outside, just import FiniteDistribution instead of DiscretizedIIDProcess.

**Comment by albop** [comment]
Here is the hierarchy for IID distributions.

![classes_distributions](https://user-images.githubusercontent.com/276777/98565199-9df99c00-22ad-11eb-8be9-a9e4e8047a31.png)

**Comment by albop** [comment]
Problem has actually been solved a while ago. Line 121 of processes.py, there is no call to DiscretizedIIDProcess anymore.
