### ISSUE TITLE
No setup.y for installation in editable mode

### ISSUE THREAD

**Issue by sbenthall** [EconForge/dolo.py#213]
According to this issue, the recommended for the use of dolark is to install dolo, dolang, and dolark from the git master branch in editable mode with `pip install -e .`

https://github.com/EconForge/dolark/issues/7

However, dolo.py currently does not have a setup.py file, which is required for installation in editable mode.

```
$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/sb/projects/econ-ark/dolo.py
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by albop** [comment]
Yes, the transition to the pyproject.toml file is a bit long. I'd say the
recommended way is to use `pip install .` instead. That one works as long
as you have installed poetry.
If you want to develop without using poetry you can use `dephell` to
generate a local `setup.py`:

```
pip install dephell # if not already installed

dephell --from=pyproject.toml --to=setup.py # only once
pip install -e . # like old times

```

**Comment by albop** [comment]
You'd have to do it, for both dolo and dolang. Now, since, people seem to
have issues, with it, I'll push temporarily a setup.py file (and remove it
in the future).

**Comment by albop** [comment]
Actually, it's not that simple. So for now, the recommended way is to `pip install .` .
if you want to develop the package, preferably use poetry. Tell me if that doesn't work for you.
