### ISSUE TITLE
Issue reading grammar on Windows

### ISSUE THREAD

**Issue by Mv77** [EconForge/dolo.py#233]
Hi,

I'm trying to work with dolo in my Windows machine, but the latest version (0.4.9.15) does not work. Running `import dolo` causes the following error
```
>>> import dolo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mateo\Anaconda3\lib\site-packages\dolo\__init__.py", line 3, in <module>
    import dolang
  File "C:\Users\mateo\Anaconda3\lib\site-packages\dolang\__init__.py", line 4, in <module>
    from dolang.grammar import parse_string
  File "C:\Users\mateo\Anaconda3\lib\site-packages\dolang\grammar.py", line 29, in <module>
    grammar_0 = open(DATA_PATH, "rt").read()
  File "C:\Users\mateo\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1179: character maps to <undefined>
```

What seems to be happening is that Windows tries to open the grammar file using the encoding `cp1252` by default, and there is a character (`0x9d`) that is not found. I wonder if there is a way to impose an encoding that would work, say
`open(DATA_PATH, "rt",encoding = "utf-8")`

**Comment by albop** [comment]
Yes, that's probably what's happening. I thought I had fixed that one a
while ago (in dolang) :
https://github.com/EconForge/dolang.py/blob/master/dolang/grammar.py

Can you check the version of dolang you are using and if it is not 0.15,
try to update it ?

**Comment by Mv77** [comment]
Updating to 0.15 did fix the issue, thanks @albop.

For some reason `pip install dolo` is installing dolang==0.0.14 for me. Did not know .15 was out. Thanks again!
